### ISSUE TITLE
Missing commas in example

### ISSUE THREAD

**Issue by cameron-jones-volusion** [ederchrono/vue-css-grid#1]
In the first example under "Usage", the `:areas` attribute should have commas after each inner array.

```
<grid
  :columns="['200px', 'auto']"
  :rows="['150px', 'auto', '100px']"
  :areas="[
    ['header', 'header']
    ['sidebar', 'main']
    ['footer', 'footer']
  ]">
```

Should be
```
  :areas="[
    ['header', 'header'],
    ['sidebar', 'main'],
    ['footer', 'footer']
  ]"
```

At least, the first one gave me an error when I tried to drop it into my project, but the second one didn't. Thanks!

**Comment by ederchrono** [comment]
You're right, I'll fix that!
