### ISSUE TITLE
Why <grid-item/> adds a display grid to itself?

### ISSUE THREAD

**Issue by moisespio** [ederchrono/vue-css-grid#2]
Is there any reason for that? Just asking because this `display: grid;` in `<grid-item/>` component forces me to create extra elements just for styling and positioning purposes.

Cheers,
Pio.

**Comment by ederchrono** [comment]
You're right, I guess I forgot to remove it after some refactoring. I'll be doing a new release with that fix shortly.

**Comment by ederchrono** [comment]
`v0.1.1` removes that unnecessary CSS
